#!/bin/sh

export PUNKAVE_PORT="8080";
export PUNKAVE_MONGODB_CONNECTION_URL='mongodb://localhost:27017';
export PUNKAVE_MONGODB_DATABASE='punkave';
export PUNKAVE_OPENWEATHERMAP_API_KEY='';
export PUNKAVE_GLOBAL_NAMESPACE='backend_challenge';